# Generated by Django 5.0.4 on 2024-04-04 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('p_mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.message')),
            ],
        ),
    ]
